version: 1.0.{build}
configuration: Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
  - master

before_build:
- dotnet restore ./src/HulkOut.sln
- choco install opencover.portable
- choco install codecov

build:
  project: ./src/HulkOut.sln

test_script:
  - dotnet test "src/HulkOut.Tests/" --logger "trx;LogFileName=HulkOut_Results.trx"

after_test:
- OpenCover.Console.exe -register:user -oldstyle -hideskipped:filter -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test src/HulkOut.Tests/" -output:"HulkOut_Coverage.xml"
- codecov -f "HulkOut_Coverage.xml"

artifacts:
- path: src\HulkOut.Tests\TestResults\HulkOut_Results.trx
- path: HulkOut_Coverage.xml
