version: 1.0.{build}
configuration: Debug

image: Visual Studio 2017

before_build:
- nuget restore ./src/HulkOut.sln
- choco install opencover.portable
- choco install codecov

build:
  project: ./src/HulkOut.sln

after_test:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\src\Tests\HulkOut.Utils.Tests\bin\Debug\net461\HulkOut.Utils.Tests.dll" -filter:"+[HulkOut.Utils*]* -[*.Tests]*" -output:"HulkOut_Coverage.xml"

- codecov -f "HulkOut_Coverage.xml"

artifacts:
- path: HulkOut_Coverage.xml
