version: 1.0.{build}
configuration: Debug

image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN:
    secure: eNNV/n8MGrIHPsyS/RvRqYrqfGYuHjos+MVQh1FWgaQX85HsO127x/7vWu4ohVYf

before_build:
- nuget restore ./src/HulkOut.sln
- choco install opencover.portable
- choco install codecov

build:
  project: ./src/HulkOut.sln

after_test:
- OpenCover.Console.exe -register:user -oldstyle -hideskipped:filter -target:"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\MSTest.exe" -targetargs:"/testcontainer:"".\src\HulkOut.Tests\bin\Debug\net461\HulkOut.Tests.dll" -filter:"+[HulkOut.*]* -[*.Tests]*" -output:"HulkOut_Coverage.xml"

- src\packages\coveralls.net.0.7.0\tools\csmacnz.Coveralls.exe --opencover -i HulkOut_Coverage.xml

artifacts:
- path: HulkOut_Coverage.xml
