version: 1.4.0.{build}
configuration: Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
  
nuget:
  disable_publish_on_pr: true

branches:
  only:
  - master
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
    - dotnet --version
    - choco install opencover.portable
    - choco install codecov

build_script:
    - dotnet build ./src/HulkOut.sln --verbosity m
  
test_script:
    - OpenCover.Console.exe -register:user -oldstyle -hideskipped:filter -target:"C:\Program Files\dotnet\dotnet.exe" -targetargs:"test ./src/HulkOut.Tests/HulkOut.Tests.csproj"  -filter:"+[HulkOut*]* -[*.Tests]*" -output:"HulkOut_Coverage.xml"

after_test:
    - codecov -f "HulkOut_Coverage.xml"

artifacts:
    - path: HulkOut_Coverage.xml
    - path: ./src/**/*.nupkg
      name: NuGet
      
deploy:
- provider: NuGet
  api_key:
    secure: vSVednxqDtvjkusy6TELf9q32+h0aa3aUqHCDsYvwGuvx2k4R3MUrn2KngWI8iNy
